### ISSUE TITLE
Crossterm backend input is not working

### ISSUE THREAD

**Issue by TimonPost** [fdehau/tui-rs#176]
I noticed, and I hear from some other people that the input of the crossterm backend is not working correctly, especially talking about the crossterm demo example. I can have a look at this in a few days, but if there are people that can do that as well it will be appreciated.

**Comment by fdehau** [comment]
This should be fixed since this commit: 9a73ead88da495ba5103f1872ec427e0b126a0cf

**Comment by TimonPost** [comment]
Alright, will have a check, would be great if the problem is already fixed :)

**Comment by TimonPost** [comment]
The crossterm demo example is wrong:

```rust
    let (tx, rx) = mpsc::channel();
    {
        let tx = tx.clone();
        thread::spawn(move || {
            let input = input();
            let reader = input.read_sync();
            for event in reader {
                match event {
                    InputEvent::Keyboard(key) => {
                        if let Err(_) = tx.send(Event::Input(key.clone())) {
                            return;
                        }
                        if key == KeyEvent::Char('q') {
                            return;
                        }
                    }
                    _ => {}
                }
            }
        });
    }
```

make it like:

```rust
    // Setup input handling
    let (tx, rx) = mpsc::channel();
    {
        let tx = tx.clone();
        thread::spawn(move || {
            let input = input();
            let mut reader = input.read_sync();
            loop {
                match reader.next() {
                    Some(InputEvent::Keyboard(key)) => {
                        if let Err(_) = tx.send(Event::Input(key.clone())) {
                            return;
                        }
                        if key == KeyEvent::Char('q') {
                            return;
                        }
                    }
                    _ => {}
                }
            }
        });
```

**Comment by fdehau** [comment]
@TimonPost Is it that the iterator might returns `None` on Windows while it does not on Linux ?

**Comment by TimonPost** [comment]
You are correct, I just discovered that in the case of windows, crossterm checks if there is an input event available for reading. If not it returns `None` directly, therefore it isn't it a blocking call. In the case of linux, a tty file read is done, which is blocking. So this should be fixed and updated in crossterm.

**Comment by TimonPost** [comment]
Can be closed, notice that this problem is fixed in crossterm 0.11

**Comment by bkaestner** [comment]
> Can be closed, notice that this problem is fixed in crossterm 0.11

Shouldn't the dependencies get updated before the issue gets closed? After all, it's still reproducible on the current `master`.

**Comment by TimonPost** [comment]
#193 fixes this
